[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_program = "A7ofZzn2ucRg1qN1dZEHTHoJr4U9trwdyifiJACkwU8C"

[programs.devnet]
solana_program = "A7ofZzn2ucRg1qN1dZEHTHoJr4U9trwdyifiJACkwU8C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/natalieyeo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
