[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_program = "6HD4mpueEPSMWMFCVraYnKC4Kyg1KJyqZLMHPJEJgh63"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/natalieyeo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
